version: '3.8'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: finalRootPwd
      MYSQL_DATABASE: finalDDb
      MYSQL_USER: finalUser
      MYSQL_PASSWORD: finalPwd
    volumes:
      - db:/var/lib/mysql
    networks:
      - FinalD_server_1
      - FinalD_server_2
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u finalUser -pfinalPwd -h db"]
      interval: 1s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: finalUser
      PMA_PASSWORD: finalPwd
    ports:
      - "8080:80"
    depends_on:
      - db

  php_1:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: php_server_1
    image: php_server_1_img
    volumes:
      - ./path/to/TP-Final-3IW-ESGI:/var/www/html
    networks:
      - FinalD_server_1
    depends_on:
      db:
        condition: service_healthy

  php_2:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: php_server_2
    image: php_server_2_img
    volumes:
      - ./path/to/TP-Final-3IW-ESGI:/var/www/html
    networks:
      - FinalD_server_2
    depends_on:
      db:
        condition: service_healthy

  nginx_1:
    build: ./nginx/
    container_name: nginx_1
    volumes:
      - ./path/to/TP-Final-3IW-ESGI:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - php_1
    environment:
      APP_SERVER_NUMBER: 1

  nginx_2:
    build: ./nginx/
    container_name: nginx_2
    volumes:
      - ./path/to/TP-Final-3IW-ESGI:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:80"
    depends_on:
      - php_2
    environment:
      APP_SERVER_NUMBER: 2

networks:
    FinalD_server_1:
    FinalD_server_2:
